// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhy0L0hAJT52eaL6OZOEGsWWUgBlT7PTc',
    appId: '1:608728058117:ios:ed1b7a683336a0e9d98f6c',
    messagingSenderId: '608728058117',
    projectId: 'echo-9cf94',
    storageBucket: 'echo-9cf94.firebasestorage.app',
    iosClientId: '608728058117-v506ssdksim6qrq7b9nbf1t5ku64rjns.apps.googleusercontent.com',
    iosBundleId: 'com.echo.echo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhy0L0hAJT52eaL6OZOEGsWWUgBlT7PTc',
    appId: '1:608728058117:ios:ed1b7a683336a0e9d98f6c',
    messagingSenderId: '608728058117',
    projectId: 'echo-9cf94',
    storageBucket: 'echo-9cf94.firebasestorage.app',
    iosClientId: '608728058117-v506ssdksim6qrq7b9nbf1t5ku64rjns.apps.googleusercontent.com',
    iosBundleId: 'com.echo.echo',
  );
}
